name: psi4 test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install psi4
      shell: bash -el {0}
      run: |
        $CONDA/bin/conda create -n p4env psi4 -c psi4
        $conda/bin/conda info
        $CONDA/bin/activate p4env
      if: always()

    - name: Install pip, wheel, pytest, jupyter
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install pytest-cov
    
    - name: Install qulacs
      run: |
        pip install qulacs
      if: always()

    - name: tangelo install
      run: |
        python -m pip install .
      if: always()

    - name: tangelo psi4 tests
      run: |
        cd dev_tools
        pytest --doctest-modules --junitxml=junit/psi4-test-results.xml test_psi4.py
      if: always()

    - name: tangelo no_pyscf tests
      run: |
        cd dev_tools
        pytest --doctest-modules --junitxml=junit/nopyscf-test-results.xml test_nopyscf.py
      if: always()

    - name: Upload nopyscf test results
      uses: actions/upload-artifact@v3
      with:
        name: tangelo-no-pyscf-test-results
        path: dev_tools/junit/nopyscf-test-results.xml

    - name: Upload psi4 test results
      uses: actions/upload-artifact@v3
      with:
        name: tangelo-psi4-test-results
        path: dev_tools/junit/psi4-test-results.xml

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      if: always()
